name: '🧪 Test'

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - dist/**
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - dist/**
jobs:
  labeler:
    name: Test Labeler
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          authToken: ${{secrets.GITHUB_TOKEN }}
          basePaths: 'test'
          prefixes: 'cat|proj'
          delimiter: ':'
          layers: 2
